<!DOCTYPE html>
<html lang="en"><head>

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>

  <title>Crystal ICT Glossary</title>

    <meta name="google-site-verification" content="-kmWUd-3GEBUndzbTqtbavE7gOmG4ojToTVpkDO4yxg" />
  <!--  Bootstrap core CSS  -->
  <link href="https://cdn.pmkg.lk/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>

  <link href="https://cdn.pmkg.lk/vendor/fontawesome-free/css/all.min.css" rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdn.pmkg.lk/vendor/simple-line-icons/css/simple-line-icons.css"/>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet"/>
  <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet"/>

  <!--  Plugin CSS  -->
  <link rel="stylesheet" href="https://pixelsign.github.io/html5-device-mockups/dist/device-mockups.min.css"/>
  <meta name="google-site-verification" content="MJiPGa-Ee6tgqE9vANTCHY8djf2An0J8i3Sph0Nm9PY" />


  <link href="https://cdn.pmkg.lk/ictg/css/new-age.min.css" rel="stylesheet"/>
  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
    {
      "@context" : "http://schema.org",
      "@type" : "SoftwareApplication",
      "name" : "Crystal ICT Glossary",
      "url" : "http://ictg.pmkg.lk/#download",
      "author" : {
        "@type" : "Organization",
        "name" : "Winter Devs"
      },
      "datePublished" : "2019-06-06",
      "publisher" : {
        "@type" : "Organization",
        "name" : "pmk-global"
      },
      "applicationCategory" : "ICT Glossary",
      "downloadUrl" : "http://ictg.pmkg.lk/download",
      "operatingSystem" : [ "Android", "Web", "Google Assistant" ],
      "offers": {
        "@type": "Offer",
        "price": "00.00",
        "priceCurrency" : "LKR",
        "url": "http://ictg.pmkg.lk/download"
      },
      "review" : {
        "@type" : "Review",
        "author" : {
          "@type" : "Person",
          "name" : "CEO - Mickfrost"
        },
        "reviewBody" : "Crystel ICT Glossary contains all the words used in ICT in both sinhala and english."
      }
    }
    </script>
    <style>
        .lds-ripple {
          display: inline-block;
          position: relative;
          width: 100px;
          height: 100px;
        }
        .lds-ripple div {
          position: absolute;
          border: 4px solid #fff;
          opacity: 1;
          border-radius: 50%;
          animation: lds-ripple 1s cubic-bezier(0, 0.2, 0.8, 1) infinite;
        }
        .lds-ripple div:nth-child(2) {
          animation-delay: -0.5s;
        }
        @keyframes lds-ripple {
          0% {
            top: 100px;
            left: 100px;
            width: 0;
            height: 0;
            opacity: 1;
          }
          100% {
            top: -1px;
            left: -1px;
            width: 100px;
            height: 100px;
            opacity: 0;
          }
        }
    </style>
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top p-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="/"><b>Crystal</b> ICT Glossary</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        @guest
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#download">Download</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#features">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/form">Master</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="/form">Master</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            </ul>
        @else
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="https://cdn.pmkg.lk/ictg/app-release.apk">Download</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#features">API</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#">help</a>
            </li>
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
        @endguest
      </div>
    </div>
  </nav>

  @yield('content')

  <footer>
    <div class="container">
      <p>&copy; <a href="https://mickftost.xyz">Winter Devs</a> @ <a href="https://www.pmkg.lk"> pmk-global</a> 2019. All Rights Reserved.</p>
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a href="#">Terms</a>
        </li>
        <li class="list-inline-item">
          <a href="#">FAQ</a>
        </li>
      </ul>
    </div>
  </footer>

  <script src="https://cdn.pmkg.lk/vendor/jquery/jquery.min.js"></script>
  <script src="https://cdn.pmkg.lk/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.pmkg.lk/vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="https://cdn.pmkg.lk/ict/js/new-age.min.js"></script>

</body>

</html>
